<?php
/**
 * Concert post type field groups
 *
 * @package    Pack_Station
 * @subpackage Fields
 * @category   ACF
 * @since      1.0.0
 */

namespace PackStation\Fields\ACF;

// Restrict direct access.
if ( ! defined( 'ABSPATH' ) ) {
	die;
}

acf_add_local_field_group(array(
	'key' => 'group_55dc856cca422',
	'title' => 'Concerts',
	'fields' => array(
		array(
			'key' => 'field_567dd25bddeef',
			'label' => 'Display',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_567dd1e2ddeee',
			'label' => 'Season',
			'name' => 'concert_season',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'season',
			'field_type' => 'radio',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_55dc8f15dd328',
			'label' => 'Date of Show',
			'name' => 'show_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'm/d/Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_567dd188ddeed',
			'label' => 'Featured Image',
			'name' => 'featured_concert_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 315,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_56f8412684e21',
			'label' => 'Info',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_56f8414684e22',
			'label' => 'Concert Information',
			'name' => 'concert_information',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_567dd26addef0',
			'label' => 'Acts',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_55dc8f882249d',
			'label' => 'Time Slot',
			'name' => 'time_slot',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_56f5cdf3e2928',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Time Slot',
			'sub_fields' => array(
				array(
					'key' => 'field_56f5cdf3e2928',
					'label' => 'Start Time',
					'name' => 'music_slot_start_time',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'g:i a',
				),
				array(
					'key' => 'field_56f5ce58e2929',
					'label' => 'End Time',
					'name' => 'music_slot_end_time',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'g:i a',
				),
				array(
					'key' => 'field_58c195167cf3c',
					'label' => 'Slot Available',
					'name' => 'music_slot_available',
					'type' => 'true_false',
					'instructions' => 'Check to add link to the sign-up form.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_58c195966bc0c',
					'label' => 'This slot is available.',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_58c195167cf3c',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'key' => 'field_55dc8fa42249e',
					'label' => 'Act',
					'name' => 'act',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_58c195167cf3c',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_55dc903e2249f',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Act to Time Slot',
					'sub_fields' => array(
						array(
							'key' => 'field_55dc903e2249f',
							'label' => 'Name of Act',
							'name' => 'act_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_55dc905b224a0',
							'label' => 'Website for Act',
							'name' => 'act_website',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://example.com/',
						),
						array(
							'key' => 'field_55dc908b224a1',
							'label' => 'Description',
							'name' => 'act_bio',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 3,
							'new_lines' => 'wpautop',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_55dc916ddb6f6',
							'label' => 'Act Thumbnail',
							'name' => 'act_thumbnail',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => 150,
							'min_height' => 150,
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg,jpeg,png',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'concert',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'author',
		1 => 'categories',
		2 => 'comments',
		3 => 'the_content',
		4 => 'format',
		5 => 'page_attributes',
		6 => 'send-trackbacks',
		7 => 'slug',
		8 => 'tags',
	),
	'active' => true,
	'description' => 'For the Concert post type. The Adams\' Pack Station Functions plugin must be activated for the post type to display.',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
));
