<?php
/**
 * Family ACF options field groups
 *
 * @package    Pack_Station
 * @subpackage Fields
 * @category   ACF
 * @since      1.0.0
 */

namespace PackStation\Fields\ACF;

// Restrict direct access.
if ( ! defined( 'ABSPATH' ) ) {
	die;
}

acf_add_local_field_group(array(
	'key' => 'group_56ff30ab43a09',
	'title' => 'Family Settings',
	'fields' => array(
		array(
			'key' => 'field_56ff30ab4b288',
			'label' => 'Template Text',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_56ff5ee5ea190',
			'label' => 'Single Family Posts',
			'name' => 'single_family_posts',
			'type' => 'divider',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_css' => '',
			'font_size' => 14,
		),
		array(
			'key' => 'field_56ff30ab4b307',
			'label' => 'Prepend Animal Name',
			'name' => 'prepend_family_name',
			'type' => 'text',
			'instructions' => 'Displays before the name in the title of single family member posts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Meet',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4b389',
			'label' => 'Append Animal Name',
			'name' => 'append_family_name',
			'type' => 'text',
			'instructions' => 'Displays after the name in the title of single family member posts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff60a91ff80',
			'label' => 'Default Description',
			'name' => 'family_excerpt_fallback',
			'type' => 'textarea',
			'instructions' => 'This is fallback text for single family posts when no description is given in the excerpt field on the family edit screen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4b485',
			'label' => 'Prepend Species Link',
			'name' => 'prepend_post_species_link',
			'type' => 'text',
			'instructions' => 'Displays on single family member posts, before the species name that links to other family members in the same species.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'View more',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4b502',
			'label' => 'Append Species Link',
			'name' => 'append_post_species_link',
			'type' => 'text',
			'instructions' => 'Displays on single family member posts, after the species name that links to other family members in the same species.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'family members »',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff5f1bea191',
			'label' => 'Family Post Archives',
			'name' => 'family_post_archives',
			'type' => 'divider',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_css' => '',
			'font_size' => 14,
		),
		array(
			'key' => 'field_56ff30ab4b57d',
			'label' => 'Archive Pages Title',
			'name' => 'family_archive_title',
			'type' => 'text',
			'instructions' => 'Displays as the title of archive pages for family member posts (<a href="http://adamspackstation.com/family/" target="_blank">adamspackstation.com/family</a>)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff5f41ea192',
			'label' => 'Family Species Archives',
			'name' => 'family_species_archives',
			'type' => 'divider',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_css' => '',
			'font_size' => 14,
		),
		array(
			'key' => 'field_56ff30ab4b5fd',
			'label' => 'Prepend Species Name',
			'name' => 'prepend_species_name',
			'type' => 'text',
			'instructions' => 'Displays before the name of the species in the title of archive pages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4b67c',
			'label' => 'Append Species Name',
			'name' => 'apppend_species_name',
			'type' => 'text',
			'instructions' => 'Displays after the name of the species in the title of archive pages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4b6fe',
			'label' => 'Family Notice',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_56ff30ab4b781',
			'label' => 'Add Family Notice',
			'name' => 'add_family_notice',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Check to add a notice to the top of family member posts & pages',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_56ff30ab4b80b',
			'label' => 'Location',
			'name' => 'family_notice_location',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_56ff30ab4b781',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'posts' => 'Single Family Member Posts',
				'archive' => 'Family Member Archive Pages',
				'season' => 'Family Member Species Pages',
			),
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'allow_custom' => 0,
			'save_custom' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_56ff30ab4b894',
			'label' => 'Family Notice',
			'name' => 'family_notice',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_56ff30ab4b781',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_56ff30ab4b916',
			'label' => 'Social Sharing',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_56ff30ab4b99d',
			'label' => 'Meta Tags for Sharing',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'The various social sites & apps, as well as some email clients, will display information about a web page when the URL (link) is pasted or typed to share with others. WordPress does not inherently offer featured images and excerpts (featured text) for archive pages. Use the settings to set what people will see when sharing a URL. The run the URL through the Facebook Debugger to "scrape" the latest information: <a href="https://developers.facebook.com/tools/debug/" target="_blank">https://developers.facebook.com/tools/debug/</a>

<a href="http://adamspackstation.com/wp-content/plugins/packstation-functions/images/aps-fb-link-example.jpg" class="thickbox" target="_blank"><strong>Example Facebook Share</strong></a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_56ff5f6bea193',
			'label' => 'Family Post Archives',
			'name' => 'family_post_archives_copy',
			'type' => 'divider',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_css' => '',
			'font_size' => 14,
		),
		array(
			'key' => 'field_56ff30ab4baa0',
			'label' => 'Archive Title',
			'name' => 'family_archive_sharing_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4bb21',
			'label' => 'Archive Description',
			'name' => 'family_archive_description',
			'type' => 'textarea',
			'instructions' => 'Maximum of 300 characters',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 300,
			'rows' => 2,
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4bba2',
			'label' => 'Archive Image',
			'name' => 'family_archive_image',
			'type' => 'image',
			'instructions' => 'It is best to upload the image to the Media Library prior to setting it here so that you can use the Post Thumbnail Editor to crop the "Sharing Image" size.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'Sharing Image',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 315,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_56ff5f87ea194',
			'label' => 'Family Species Archives',
			'name' => 'family_species_archives_copy',
			'type' => 'divider',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'custom_css' => '',
			'font_size' => 14,
		),
		array(
			'key' => 'field_56ff30ab4bc24',
			'label' => 'Prepend Species Name',
			'name' => 'prepend_species_archive_name',
			'type' => 'text',
			'instructions' => 'Displays before the name of the species.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4bca7',
			'label' => 'Append Species Name',
			'name' => 'append_species_archive_name',
			'type' => 'text',
			'instructions' => 'Displays after the name of the species.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4bd29',
			'label' => 'Species Archive Description',
			'name' => 'species_archive_description',
			'type' => 'textarea',
			'instructions' => 'This must be a general description for a species types.<br />
Maximum of 300 characters.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 300,
			'rows' => 2,
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff30ab4bd89',
			'label' => 'Species Archive Image',
			'name' => 'species_archive_image',
			'type' => 'image',
			'instructions' => 'It is best to upload the image to the Media Library prior to setting it here so that you can use the Post Thumbnail Editor to crop the "Sharing Image" size.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'Sharing Image',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 315,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'family-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Family Settings page. The Adams\' Pack Station Functions plugin must be activated for the options page to display.',
));
