<?php
/**
 * Concert ACF options field groups
 *
 * @package    Pack_Station
 * @subpackage Fields
 * @category   ACF
 * @since      1.0.0
 */

namespace PackStation\Fields\ACF;

// Restrict direct access.
if ( ! defined( 'ABSPATH' ) ) {
	die;
}

acf_add_local_field_group( array(
	'key'    => 'group_56feb32807797',
	'title'  => 'Concert Settings',
	'fields' => array(
		array(
			'key' => 'field_56fedd031a874',
			'label' => 'Template Text',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_56fee2e867a4c',
			'label' => 'Prepend Concert Date',
			'name' => 'prepend_concert_date',
			'type' => 'text',
			'instructions' => 'Displays before the date in the title of single concert posts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56fee31e67a4d',
			'label' => 'Append Concert Date',
			'name' => 'append_concert_date',
			'type' => 'text',
			'instructions' => 'Displays after the date in the title of single concert posts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff02088fe0a',
			'label' => 'Title for Concert Lineup',
			'name' => 'lineup_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Scheduled Acts',
			'placeholder' => 'Scheduled Acts',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_56ff5393bfe76',
			'label' => 'Default Description',
			'name' => 'concert_excerpt_fallback',
			'type' => 'textarea',
			'instructions' => 'This is fallback text for single concert posts when no description is given in the excerpt field on the concert edit screen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56feff86b889a',
			'label' => 'Prepend Season Link',
			'name' => 'prepend_post_season_link',
			'type' => 'text',
			'instructions' => 'Displays on single concert posts, before the year that links to other concerts in the same season.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'View more',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56ff0099b889b',
			'label' => 'Append Season Link',
			'name' => 'append_post_season_link',
			'type' => 'text',
			'instructions' => 'Displays on single concert posts, after the year that links to other concerts in the same season.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'concerts »',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56fedd2c1a875',
			'label' => 'Archive Pages Title',
			'name' => 'concert_archive_title',
			'type' => 'text',
			'instructions' => 'Displays as the title of archive pages for concert posts (<a href="http://adamspackstation.com/concerts/" target="_blank">adamspackstation.com/concerts</a>)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_570021669c764',
			'label' => 'Concert Link Text',
			'name' => 'concert_link_text',
			'type' => 'text',
			'instructions' => 'Text on the archive and season pages that links to the single concert post.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'View Details',
			'placeholder' => 'View Details',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56fedece76515',
			'label' => 'Prepend Season Year',
			'name' => 'prepend_season_year',
			'type' => 'text',
			'instructions' => 'Displays before the year of the concert season in the title of archive pages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56fee03049ec3',
			'label' => 'Append Season Year',
			'name' => 'apppend_season_year',
			'type' => 'text',
			'instructions' => 'Displays after the year of the concert season in the title of archive pages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56fee60b023cd',
			'label' => 'Concert Notice',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_56fee62b023ce',
			'label' => 'Add Concert Notice',
			'name' => 'add_concert_notice',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Check to add a notice to the top of concert posts & pages',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_56fee69b023cf',
			'label' => 'Location',
			'name' => 'concert_notice_location',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_56fee62b023ce',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'posts' => 'Single Concert Posts',
				'archive' => 'Concert Archive Pages',
				'season' => 'Concert Season Pages',
			),
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'allow_custom' => 0,
			'save_custom' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_56fee757023d0',
			'label' => 'Concert Notice',
			'name' => 'concert_notice',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_56fee62b023ce',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_56feb390d9580',
			'label' => 'Social Sharing',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_56feb3a6d9581',
			'label' => 'Meta Tags for Sharing',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'The various social sites & apps, as well as some email clients, will display information about a web page when the URL (link) is pasted or typed to share with others. WordPress does not inherently offer featured images and excerpts (featured text) for archive pages. Use the settings to set what people will see when sharing a URL. The run the URL through the Facebook Debugger to "scrape" the latest information: <a href="https://developers.facebook.com/tools/debug/" target="_blank">https://developers.facebook.com/tools/debug/</a>

<a href="http://adamspackstation.com/wp-content/plugins/packstation-functions/images/aps-fb-link-example.jpg" class="thickbox" target="_blank"><strong>Example Facebook Share</strong></a>',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_56feb7ae3be0c',
			'label' => 'Archive Title',
			'name' => 'concert_archive_sharing_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56feb7d03be0d',
			'label' => 'Archive Description',
			'name' => 'concert_archive_description',
			'type' => 'textarea',
			'instructions' => 'Maximum of 300 characters',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 300,
			'rows' => 2,
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56feba5ed9516',
			'label' => 'Archive Image',
			'name' => 'concert_archive_image',
			'type' => 'image',
			'instructions' => 'It is best to upload the image to the Media Library prior to setting it here so that you can use the Post Thumbnail Editor to crop the "Sharing Image" size.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'Sharing Image',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 315,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_56feb9e1ddecc',
			'label' => 'Prepend Season Year',
			'name' => 'prepend_season_archive_year',
			'type' => 'text',
			'instructions' => 'Displays before the year of the season.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Adams\' Pack Station',
			'placeholder' => 'Adams\' Pack Station',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56fec26f65835',
			'label' => 'Append Season Year',
			'name' => 'apppend_season_archive_year',
			'type' => 'text',
			'instructions' => 'Displays after the year of the season.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Concerts',
			'placeholder' => 'Concerts',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56feba06ddecd',
			'label' => 'Season Archive Description',
			'name' => 'concert_season_description',
			'type' => 'textarea',
			'instructions' => 'Maximum of 300 characters',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 300,
			'rows' => 2,
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_56febb1ed9517',
			'label' => 'Seasons Archive Image',
			'name' => 'concert_season_image',
			'type' => 'image',
			'instructions' => 'It is best to upload the image to the Media Library prior to setting it here so that you can use the Post Thumbnail Editor to crop the "Sharing Image" size.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'Sharing Image',
			'library' => 'all',
			'min_width' => 600,
			'min_height' => 315,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'concert-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Concert Settings page. Concert post type and archives. The Adams\' Pack Station Functions plugin must be activated for the options page to display.',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
));
